config/routes.rb
Rails.application.routes.draw do


  resources :dogs, only: [:index, :show], formats: [:json, :html]
  resources :shelters, only: [:index, :show]
  resources :breeds, only: [:index, :show]

  root to: 'visitors#index'
end

app/models/breed.rb
class Breed < ActiveRecord::Base
  include Sluggable

  has_many :dogs

  default_scope -> { order(:name) }

  def dog_image_url
    return self.image_url unless self.image_url.blank?

    if self.dogs.count > 0
      self.image_url = self.dogs.first.image_url
      self.save
      return self.image_url
    else
      return ""
    end


  end

end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    after_create :generate_slug
  end

  def generate_slug
    if self.slug.blank?
      self.slug = "#{self.name} #{self.id unless self.is_a?(Shelter)}".parameterize
      self.save
    end

  end

  def to_param
    return self.slug unless self.slug.blank?
    return self.id.to_s
  end

  module ClassMethods
    def find(id)
      if id.is_numeric?
        super(id)
      else
        found = find_by_slug(id)
        if found.nil?
          raise ActiveRecord::RecordNotFound
        else
          return found
        end
      end
    end
  end
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  include Sluggable

  belongs_to :shelter
  belongs_to :breed

  validates :name, :shelter_url, :image_url, :description, :breed, :shelter, presence: true

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  include Sluggable
  
  has_many :dogs

  default_scope -> { order(:name) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  respond_to :json, :html

  def index
    @breeds = Breed.all

    
    respond_with @breeds do |format|
      format.html
      format.json { render json: {breeds: @breeds}}
    end

  end

  def show
    @breed = Breed.find(params[:id])
    @dogs = @breed.dogs

    respond_with @breed do |format|
      format.html
      format.json { render json: { breed: @breed }}
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  respond_to :json, :html

  def index
    @dogs = Dog.all

    respond_with @dogs do |format|
      format.html
      format.json { render json: {dogs: @dogs} }
    end
  end

  def show
    @dog = Dog.find(params[:id])

    respond_with(@dog) do |format|
      format.html
      format.json { render json: {dog: @dog} }
    end
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  respond_to :json, :html


  def index
    @shelters = Shelter.all
    
    respond_with @shelters do |format|
      format.html
      format.json { render json: { shelters: @shelters }}
    end
  end

  def show
    @shelter = Shelter.find(params[:id])
    @dogs = @shelter.dogs

    respond_with @shelter do |format|
      format.html
      format.json { render json: { shelter: @shelter } }
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController


  def index
    @shelters = Shelter.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/breeds/index.html.haml
.row
  .col-md-12
    %h1 Breeds
    %hr

.row
  .col-md-12
    .dog-list
      -@breeds.each do |breed|
        .col-md-4
          .dog-list-item{id: "breed-#{breed.id}", style: "background-image: url('#{breed.dog_image_url}');"}
            %a{href: breed_url(breed)}
              %p.caption=breed.name

app/views/breeds/show.html.haml
.row
  .col-md-12
    %h1=@breed.name
    %p
      =link_to "&#8592; Back to Breeds".html_safe, breeds_url
    %hr

.row
  .col-md-12
    =render partial: "dogs/dog_list", locals: {dogs: @dogs}

app/views/dogs/_dog_list.html.haml
.dog-list
  -dogs.each do |dog|
    .col-md-4
      .dog-list-item{id: "dog-list-#{dog.id}", style: "background-image: url('#{dog.image_url}');"}
        %a{href: dog_url(dog)}
          %p.caption=dog.name

app/views/dogs/index.html.haml
.row
  .col-md-12
    %h1 Find a Dog
    %hr

.row
  .col-md-12
    =render partial: "dog_list", locals: {dogs: @dogs}

app/views/dogs/show.html.haml
.row
  .col-md-12
    %h1=@dog.name
    %p.dogs-index-link
      =link_to "&#8592; Back to Dogs".html_safe, dogs_url 
    %hr

.row
  .col-md-6
    .dog-image
      =image_tag @dog.image_url
  .col-md-6
    %br
    .dog-description=simple_format @dog.description
    %br
    %p
      =link_to "View Full Details", @dog.shelter_url, target: "_blank", class: "btn btn-primary btn-large"
    %hr
    %ul
      -if @dog.age_string || @dog.date_of_birth
        %li
          %p
            -if @dog.date_of_birth
              %strong Date of Birth:
              #{@dog.date_of_birth} (#{time_ago_in_words(@dog.date_of_birth)})
            -else
              %strong Approximate Age:
            =@dog.age_string

      -if @dog.is_female
        %li
          %p
            %strong Gender:
            =@dog.is_female ? "Female" : "Male"

      -if @dog.breed
        %li
          %p
            %strong Breed:
            =link_to @dog.breed.name, breed_url(@dog.breed)

      -if @dog.shelter
        %li
          %p
            %strong Shelter:
            =link_to @dog.shelter.name, shelter_url(@dog.shelter)

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  =link_to "Find a Dog", dogs_path

%li
  =link_to  "Birmingham Dog Shelters", shelters_path

%li
  =link_to "Breeds List", breeds_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Adopt a Dog in Birmingham, UK'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Dogs'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .container
      .shunt
      = render 'layouts/messages'
      = yield

app/views/shelters/index.html.haml
.row
  .col-md-12
    %h1 Birmingham Dog Shelters
    %hr

.row
  .col-md-12
    -@shelters.each do |shelter|
      .row
        .shelter-item{id: "shelter-#{shelter.id}"}  
          .col-md-8
            %h2=link_to shelter.name, shelter_url(shelter)
            %br
            .shelter-description
              =simple_format shelter.description
            %breed_spec
            %p=link_to "Details", shelter_url(shelter), class: "btn btn-primary"
          .col-md-4
            -if shelter.image_url
              =image_tag shelter.image_url, alt: shelter.name
            -else
              &nbsp;

app/views/shelters/show.html.haml
.row
  .col-md-12
    %h1=@shelter.name
    %p
      =link_to "&#8592; Back to Shelters".html_safe, shelters_url
    %hr

.row
  .col-md-4
    -if @shelter.image_url
      .shelter-image
        =image_tag @shelter.image_url, alt: @shelter.name
  .col-md-8
    %h3 About #{@shelter.name}
    %br
    .shelter-description
      =simple_format @shelter.description
    %br
    %p
      =link_to "View Shelter's Website", @shelter.url, class: "btn btn-primary btn-large", target: "_blank"
      =link_to "View Contact Details", @shelter.contact_details, class: "btn  btn-large", target: "_blank"


.row

  .col-md-12
    %h3 Dogs at #{@shelter.name}
    %hr
    =render partial: "dogs/dog_list", locals: {dogs: @shelter.dogs}

app/views/visitors/index.html.haml
.row
  .col-md-12
    %h1 Adopt a Dog in Birmingham, UK
    %hr
    %p Adopt a Dog is a free service for finding rescue dogs available for re-homing in Birmingham.
    %p Dogs listed on this site are found from the following dog shelters from around Birmingham:

    %ul
      -@shelters.each do |shelter|
        %li
          =link_to shelter.name, shelter_url(shelter)